version: "3"

services:
  backend:
    build: ./
    container_name: qr-code
    working_dir: /qr-code
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    volumes:
      - static_content:/qr-code/src/static/
      - ./src:/qr-code/src
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:1.19
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_content:/qr-code/src/static/
      - ./nginx:/etc/nginx/conf.d
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  static_content: { }
