# Generated by Django 4.1.4 on 2022-12-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
