# Generated by Django 4.1.4 on 2023-01-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="title",
            field=models.CharField(
                blank=True, default=None, max_length=50, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="message",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=256,
                null=True,
                verbose_name="message",
            ),
        ),
    ]
