# Generated by Django 4.1.4 on 2023-01-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_qrcode_title_alter_qrcode_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='message',
            field=models.CharField(blank=True, default='Sorry for blocking you. BRB!', max_length=256, null=True, verbose_name='message'),
        ),
    ]
