# Generated by Django 4.1.4 on 2023-01-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_qrcode_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrcode",
            name="password",
        ),
    ]
