# Generated by Django 4.1.4 on 2022-12-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_qrcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='hash',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True, verbose_name='hash'),
        ),
    ]
