# Generated by Django 4.1.4 on 2022-12-12 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_qrcode_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='message',
            field=models.CharField(blank=True, default=None, max_length=140, null=True, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
